yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment',
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
    )

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Имя группы',
        help_text='Введи имя группы',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Слаг',
        help_text='Подбери уникальный слаг',
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Опиши',
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        db_index=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="posts",
        verbose_name='Группа',
        help_text='Выберите группу',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        ordering = ('-pub_date', )
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Пост, к которому будет оставлен комментарий',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='comments',
        blank=True,
        null=True,
        verbose_name='Автор комментария',
    )
    text = models.TextField(
        null=True,
        max_length=100,
        verbose_name='Текст комментария',
        help_text='Текст нового комментария',
    )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата публикации комментария',
    )

    class Meta:
        ordering = ('-created', )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        blank=True,
        null=True,
        verbose_name='Имя подписчика',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        blank=True,
        null=True,
        verbose_name='Имя автора',
    )

    class Meta:
        constraints = (models.UniqueConstraint(fields=('user', 'author'),
                                               name='unique_following'), )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = 'text', 'group', 'image'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = 'text',

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.urls import reverse

from .forms import PostForm, CommentForm
from .models import Follow, Group, Post
from .paginator import get_page_obj

User = get_user_model()


@cache_page(20)
def index(request):
    post_list = Post.objects.all()
    template = "posts/index.html"
    context = {
        "page_obj": get_page_obj(request, post_list),
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = "posts/group_list.html"
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    context = {
        "group": group,
        "page_obj": get_page_obj(request, posts),
    }
    return render(request, template, context)


def profile(request, username):
    template = "posts/profile.html"
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author).exists()

    context = {
        "author": author,
        "page_obj": get_page_obj(request, posts),
        "following": following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    form = CommentForm()
    user_posts_count = post.author.posts.all().count()
    context = {
        "post": post,
        'comments': comments,
        'form': form,
        "user_posts_count": user_posts_count,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        author = request.user
        form.instance.author = author
        form.save()
        return redirect(reverse("posts:profile", args=[author.username]))
    return render(request, "posts/post_create.html", {"form": form})


@login_required
def post_edit(request, post_id):
    template = "posts/post_create.html"
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect("posts:post_detail", post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect(reverse("posts:post_detail", args=[post_id]))
    context = {
        "form": form,
        "is_edit": True,
        "post": post,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user)
    context = {"page_obj": get_page_obj(request, posts)}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(
            user=user,
            author=author,
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        user=request.user, author__username=username).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/comments.html
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text}}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Вы подписаны на авторов{% endblock %}
{% block header %} Посты авторов, на которых вы подписаны {% endblock %}
{% load cache %}
{% cache 20 index_page %}
  {% block content %}
  {% include "posts/includes/switcher.html" with follow=True %}
  {% load thumbnail %}
        <div class="container py-5">
    {% for post in page_obj %}
      {% include 'includes/post_card.html' %}
      {% if not forloop.last %}<hr/>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  {% endblock %}
</div>
{% endcache %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <hr />
    <p>{{ group.description }}</p>
    <hr />
    {% for post in page_obj %}
      {% include 'includes/post_card.html' %}
      {% if not forloop.last %}<hr />{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
    Последние обновления на сайте
{% endblock %}
{% block content %}
{#    {% load cache %}#}
{#{% cache 20 index_page %}#}
    {% include 'posts/includes/switcher.html' with index=True %}

  <div class="container py-5">
    {% for post in page_obj %}
      {% include 'includes/post_card.html' %}
      {% if not forloop.last %}<hr/>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{#  {% endcache %}#}

{% endblock %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}
{% block title %}
    {% if is_edit %}
        Редактирование записи
    {% else %}
        Создание записи
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container py-5">
        <h3>
            {% if is_edit %}
                Редактирование записи
            {% else %}
                Создание записи
            {% endif %}
        </h3>
        <form method="post"
              action="{% if is_edit %}{% url 'posts:post_edit' post.id %}{% else %}{% url 'posts:post_create' %}{% endif %}"
              enctype="multipart/form-data"
        >{% csrf_token %}
            {% for field in form %}
                <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                        {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                    </label>
                    {{ field }}
                    {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                        Сохранить
                    {% else %}
                        Добавить
                    {% endif %}
                </button>
            </div>
        </form>
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ post.text|slice:":30" }}{% endblock %}
{% block content %}
    {% load thumbnail %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          </li>
        {% endif %}
        <li class="list-group-item">Автор: {{ post.author.get_full_name }}</li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span >{{ user_posts_count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      <p>{{ post.text }}</p>
    {% include 'posts/comments.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ user.username }}{% endblock %}
{% block content %}
    <div class="container py-5">
        <h1>Все посты пользователя {{ user.username }}</h1>
        <h3>Всего постов: {{ author.posts.count }}</h3>
    {% if user.is_authenticated %}
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
   {% endif %}
        {% for post in page_obj %}
            {% include 'includes/post_card.html' %}
            {% if not forloop.last %}<hr/>{% endif %}
        {% endfor %}
        <!-- Остальные посты. после последнего нет черты -->
        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}